spring.application.name=Livraime
server.port=8081

# URL de conexão JDBC para H2 (persistência em disco)
spring.datasource.url=jdbc:h2:file:./data/database;DB_CLOSE_ON_EXIT=FALSE

# Não precisa de usuário e senha
spring.datasource.username=sa
spring.datasource.password=

# Driver JDBC do H2
spring.datasource.driver-class-name=org.h2.Driver

# Segundo banco de dados externo ONLINE (não salva em disco).
# Substitua este URL pelo banco remoto real quando disponível.
# Exemplo PostgreSQL remoto:
# spring.external-datasource.url=jdbc:postgresql://db.example.com:5432/externaldb
spring.external-datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.gcepldgahlxxrzrqejkd&password=Enr60dyrkZKpkXpx
spring.external-datasource.username=postgres.gcepldgahlxxrzrqejkd
spring.external-datasource.password=Enr60dyrkZKpkXpx
spring.external-datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) - configurações adicionais (usa apenas o banco H2 local)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# (Opcional) Definir timezone para evitar warnings
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# H2 Console habilitado (para debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === SPRING MAIL (envio de e-mails via Gmail SMTP) ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=livraimeofficial@gmail.com
spring.mail.password=fnkq qdsx rwjs hilj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
